<?xml version="1.0" encoding="UTF-8"?><rss version="2.0"
	xmlns:content="http://purl.org/rss/1.0/modules/content/"
	xmlns:dc="http://purl.org/dc/elements/1.1/"
	xmlns:atom="http://www.w3.org/2005/Atom"
	xmlns:sy="http://purl.org/rss/1.0/modules/syndication/"
	xmlns:georss="http://www.georss.org/georss" xmlns:geo="http://www.w3.org/2003/01/geo/wgs84_pos#" 
	>
<channel>
	<title>Comments on: Résoudre l&#8217;erreur Python ImportError: cannot import name urandom</title>
	<atom:link href="http://sametmax.com/resoudre-importerror-cannot-import-name-urandom/feed/" rel="self" type="application/rss+xml" />
	<link>http://sametmax.com/resoudre-importerror-cannot-import-name-urandom/</link>
	<description>Du code, du cul</description>
	<lastBuildDate>Fri, 06 Sep 2019 09:34:15 +0000</lastBuildDate>
	<sy:updatePeriod>hourly</sy:updatePeriod>
	<sy:updateFrequency>1</sy:updateFrequency>
	<generator>https://wordpress.org/?v=4.9.7</generator>
	<item>
		<title>By: Sam</title>
		<link>http://sametmax.com/resoudre-importerror-cannot-import-name-urandom/#comment-700</link>
		<dc:creator><![CDATA[Sam]]></dc:creator>
		<pubDate>Wed, 18 Jul 2012 14:32:05 +0000</pubDate>
		<guid isPermaLink="false">http://sametmax.com/?p=1170#comment-700</guid>
		<description><![CDATA[Explication intéressante et toujours la bienvenue.]]></description>
		<content:encoded><![CDATA[<p>Explication intéressante et toujours la bienvenue.</p>
]]></content:encoded>
	</item>
	<item>
		<title>By: Brutasse</title>
		<link>http://sametmax.com/resoudre-importerror-cannot-import-name-urandom/#comment-699</link>
		<dc:creator><![CDATA[Brutasse]]></dc:creator>
		<pubDate>Wed, 18 Jul 2012 13:42:37 +0000</pubDate>
		<guid isPermaLink="false">http://sametmax.com/?p=1170#comment-699</guid>
		<description><![CDATA[Ça vient de la dernière mise à jour de Python qui ajoute la &quot;hash randomization&quot;. Ça touche à os.urandom, d&#039;où l&#039;erreur d&#039;import. Recréer le virtualenv est effectivement la solution, de toute façon ils sont jetables :).]]></description>
		<content:encoded><![CDATA[<p>Ça vient de la dernière mise à jour de Python qui ajoute la &#8220;hash randomization&#8221;. Ça touche à os.urandom, d&#8217;où l&#8217;erreur d&#8217;import. Recréer le virtualenv est effectivement la solution, de toute façon ils sont jetables :).</p>
]]></content:encoded>
	</item>
	<item>
		<title>By: Sortir de virtualenv &#8211; Exit &#124; Sam &#38; Max: Python, Django, Git et du cul</title>
		<link>http://sametmax.com/resoudre-importerror-cannot-import-name-urandom/#comment-697</link>
		<dc:creator><![CDATA[Sortir de virtualenv &#8211; Exit &#124; Sam &#38; Max: Python, Django, Git et du cul]]></dc:creator>
		<pubDate>Wed, 18 Jul 2012 13:33:51 +0000</pubDate>
		<guid isPermaLink="false">http://sametmax.com/?p=1170#comment-697</guid>
		<description><![CDATA[[...] liens sur virtualenv: - Résoudre l’erreur Python ImportError: cannot import name urandom - Travailler moins pour gagner plus, en 15 minutes avec Python fabric [...]]]></description>
		<content:encoded><![CDATA[<p>[&#8230;] liens sur virtualenv: &#8211; Résoudre l’erreur Python ImportError: cannot import name urandom &#8211; Travailler moins pour gagner plus, en 15 minutes avec Python fabric [&#8230;]</p>
]]></content:encoded>
	</item>
	<item>
		<title>By: Sam</title>
		<link>http://sametmax.com/resoudre-importerror-cannot-import-name-urandom/#comment-689</link>
		<dc:creator><![CDATA[Sam]]></dc:creator>
		<pubDate>Tue, 17 Jul 2012 22:20:58 +0000</pubDate>
		<guid isPermaLink="false">http://sametmax.com/?p=1170#comment-689</guid>
		<description><![CDATA[Par contre je suppose que tu veux dire &lt;code&gt;--setuptools&lt;/code&gt; car distribute est le comportement par défaut dans les derniers virtualenvs.]]></description>
		<content:encoded><![CDATA[<p>Par contre je suppose que tu veux dire <code>--setuptools</code> car distribute est le comportement par défaut dans les derniers virtualenvs.</p>
]]></content:encoded>
	</item>
	<item>
		<title>By: Encolpe DEGOUTE</title>
		<link>http://sametmax.com/resoudre-importerror-cannot-import-name-urandom/#comment-688</link>
		<dc:creator><![CDATA[Encolpe DEGOUTE]]></dc:creator>
		<pubDate>Tue, 17 Jul 2012 20:03:31 +0000</pubDate>
		<guid isPermaLink="false">http://sametmax.com/?p=1170#comment-688</guid>
		<description><![CDATA[&lt;span class=&quot;merci&quot;&gt;&lt;/span&gt;Il faut remettre les mêmes options que lors de la création du virtualenv (--python et --distribute).]]></description>
		<content:encoded><![CDATA[<p><span class="merci"></span>Il faut remettre les mêmes options que lors de la création du virtualenv (&#8211;python et &#8211;distribute).</p>
]]></content:encoded>
	</item>
</channel>
</rss>
